In [1]:
import tensorflow as tf
import numpy as np

/Users/monk/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/monk/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [15]:
tf.reset_default_graph()

input_data = np.random.randint(0,10,[10,150,10]).astype(np.float32)
# print(input_data)

labels     = np.random.randint(0,10,[10,150])
print(labels)
sequence_length = np.random.randint(5,10,[10])




logits =       tf.placeholder(dtype=tf.float32,shape=[10,150,10])
labels_a =     tf.placeholder(dtype=tf.int32,shape=[10,150])
sequence_len =  tf.placeholder(dtype=tf.int32,shape=[10])


# logits :       A [batch_size, max_seq_len, num_tags] tensor of unary potentials to use as input to the CRF layer.

# labels_a :     A [batch_size, max_seq_len] matrix of tag indices for which we compute the log-likelihood.

# sequence_len : A [batch_size] vector of true sequence lengths.

[[6 6 3 ... 4 1 1]
 [7 0 1 ... 4 1 3]
 [0 8 2 ... 3 9 4]
 ...
 [1 9 1 ... 2 2 1]
 [0 1 1 ... 2 1 9]
 [0 6 5 ... 7 7 6]]


In [16]:
log_likelihood , transition_params = tf.contrib.crf.crf_log_likelihood(logits,labels_a,sequence_len)

#return of crf log_likelihood function

# log_likelihood: A scalar containing the log-likelihood of the given sequence of tag indices.
    
# transition_params: A [num_tags, num_tags] transition matrix. 
# This is either provided by the caller or created in this function.

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    log,transition = sess.run([log_likelihood , transition_params],feed_dict={logits:input_data,labels_a:labels,sequence_len:sequence_length})
    print(log)
    print('\n\n\n')
    print(transition)
    
    

[-26.751984 -39.12082  -23.732555 -31.0827   -54.15993  -27.738861
 -39.98494  -39.400642 -35.378098 -29.526867]




[[ 0.0597254  -0.18939969 -0.37308615 -0.1557309  -0.54387236 -0.18239656
   0.44735038  0.14592278  0.28721112 -0.2440784 ]
 [ 0.36213928  0.2651016  -0.14881057  0.51535153 -0.39267856  0.30944604
  -0.21720496  0.4870596  -0.02661616  0.34865993]
 [-0.20212436  0.33483636 -0.46566105 -0.37441647  0.37160206  0.06753802
  -0.4331742  -0.41929865 -0.4389946  -0.29370037]
 [ 0.08166194 -0.35071632 -0.52802795 -0.42154866 -0.52359176  0.07828969
  -0.16364527  0.20560712 -0.02793193  0.16354   ]
 [-0.09920922  0.2803282   0.32725173 -0.47650865 -0.11156759 -0.3297739
   0.528862   -0.44445276 -0.3236537   0.09304971]
 [-0.11195898  0.52115726  0.28728724 -0.35106826 -0.35146746 -0.51949054
   0.38777304 -0.28410807  0.47912037  0.53176105]
 [-0.17654115 -0.03193027  0.34621352  0.17824453 -0.31043264  0.28358078
  -0.38455865 -0.4462499  -0.1393452   0.38169384]
 [ 0.2149